/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jeudupendu;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author 633-086163
 */
public class accueilFrame extends javax.swing.JFrame {

    public GestionJeu ges = null;
    /**
     * Creates new form accueilFrame
     */
    public accueilFrame() {
        super("Le jeu du Pendu");
        ges = new GestionJeu();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nomJoueurText = new javax.swing.JTextField(15);
        startGamebutt = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        resetMenu = new javax.swing.JMenu();
        startGame = new javax.swing.JMenuItem();
        infoMenu = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        quitGameMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Le jeu du Pendu");

        jLabel2.setText("ACME International ©");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nom de joueur : ");

        nomJoueurText.setAlignmentX(5.0F);
        nomJoueurText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nomJoueurText.setMaximumSize(new java.awt.Dimension(2, 16));

        startGamebutt.setText("Débuter la partie!");
        startGamebutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startGamebuttActionPerformed(evt);
            }
        });

        resetMenu.setText("Menu");

        startGame.setText("Débuter la partie");
        startGame.setEnabled(false);
        resetMenu.add(startGame);

        infoMenu.setText("À propos...");
        infoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoMenuActionPerformed(evt);
            }
        });
        resetMenu.add(infoMenu);

        jMenuItem1.setText("Réinitialiser la partie");
        jMenuItem1.setEnabled(false);
        resetMenu.add(jMenuItem1);

        quitGameMenu.setText("Quitter le jeu");
        quitGameMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitGameMenuActionPerformed(evt);
            }
        });
        resetMenu.add(quitGameMenu);

        jMenuBar1.add(resetMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(102, 102, 102))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(142, 142, 142))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomJoueurText, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(startGamebutt, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomJoueurText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(startGamebutt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void infoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoMenuActionPerformed
     JOptionPane.showMessageDialog(null, "Règles du jeu : \nEssaie de deviner le mot caché en utilisant les lettres de l'alphabet \navant que le petit bonhomme se fasse pendre. Sa vie est entre tes mains. \nTu as droit 6 erreurs avant d'être témoin d'une pendaison.\n1 point/lettre devinée.", "Règles du jeu", 1);   // TODO add your handling code here:
    }//GEN-LAST:event_infoMenuActionPerformed

    private void startGamebuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startGamebuttActionPerformed
        
        
        String nom ="";                
        if ("".equals(nomJoueurText.getText()))
        {
           nom = "Player One";          
        }
        else
        {
            nom = nomJoueurText.getText();
            if (nom.length() > 15)
            {
                nom = nom.substring(0,12);
                JOptionPane.showMessageDialog(null, "Votre nom était trop long, il a été modifié pour : " +nom);
            }
        }            
            this.setVisible(false);
            this.dispose();
            platformeJeu newG = new platformeJeu(ges, nom);
            newG.setVisible(true);
        
        
       

        
    }//GEN-LAST:event_startGamebuttActionPerformed

    private void quitGameMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitGameMenuActionPerformed
        System.exit(0);
    }//GEN-LAST:event_quitGameMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(accueilFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(accueilFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(accueilFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(accueilFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new accueilFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem infoMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JTextField nomJoueurText;
    private javax.swing.JMenuItem quitGameMenu;
    private javax.swing.JMenu resetMenu;
    private javax.swing.JMenuItem startGame;
    private javax.swing.JButton startGamebutt;
    // End of variables declaration//GEN-END:variables
}
