/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aubergefdl;

import java.util.Arrays;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.*;

/**
 *
 * @author simonlegosu
 */
public class payeFrame extends javax.swing.JFrame {

    public gestion ges = null;
    /**
     * Creates new form payeFrame
     */
    public payeFrame() {
        initComponents();
        empComboBox.setModel(new javax.swing.DefaultComboBoxModel(ges.Emp.toArray()));
    }
        public payeFrame(gestion ges)
    {        
        initComponents();
        this.ges = ges;
        empComboBox.setModel(new javax.swing.DefaultComboBoxModel(ges.Emp.toArray()));
        String popo = empComboBox.getSelectedItem().toString();
        String[] parts = popo.split("     ");
        String part3 = parts[2];
        if ("Ventes".equals(part3))
        {
            venteText.setEnabled(true);
        }
        else
        {
            venteText.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        semaineEnCoursField = new javax.swing.JTextField();
        contRrField = new javax.swing.JTextField();
        assEmpField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        dateField = new javax.swing.JTextField();
        otEmpButt = new javax.swing.JButton();
        otDepartButt = new javax.swing.JButton();
        vendeursButt = new javax.swing.JButton();
        venteMoisbutt = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        heureText = new javax.swing.JTextField();
        submitPayeButt = new javax.swing.JButton();
        empComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        venteText = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        affichage = new javax.swing.JEditorPane();
        listeEmpText = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Auberge Fleur de Lys - PAYE");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Semaine en cours : ");

        jLabel2.setText("Total contributions régime retraite Canada : ");

        jLabel3.setText("Total contribitions assurance emploi : ");

        semaineEnCoursField.setEditable(false);

        contRrField.setEditable(false);

        assEmpField.setEditable(false);

        jLabel7.setText("Date : ");

        dateField.setEditable(false);

        otEmpButt.setText("Voir overtime par employé");
        otEmpButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otEmpButtActionPerformed(evt);
            }
        });

        otDepartButt.setText("Voir overtime par département");
        otDepartButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otDepartButtActionPerformed(evt);
            }
        });

        vendeursButt.setText("Voir vendeurs");
        vendeursButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendeursButtActionPerformed(evt);
            }
        });

        venteMoisbutt.setText("Voir Vente par mois");
        venteMoisbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venteMoisbuttActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(otEmpButt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vendeursButt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(otDepartButt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(assEmpField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(contRrField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(2, 2, 2)
                                .addComponent(semaineEnCoursField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dateField)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(venteMoisbutt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(semaineEnCoursField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(contRrField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(assEmpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(otEmpButt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(otDepartButt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vendeursButt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(venteMoisbutt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Numéro d'employé : ");

        jLabel5.setText("Heures travaillé : ");

        heureText.setMaximumSize(new java.awt.Dimension(59, 20));
        heureText.setMinimumSize(new java.awt.Dimension(59, 20));
        heureText.setPreferredSize(new java.awt.Dimension(59, 20));

        submitPayeButt.setText("Soumettre");
        submitPayeButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitPayeButtActionPerformed(evt);
            }
        });

        empComboBox.setMaximumRowCount(20);
        empComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ges.Emp.toArray()" }));
        empComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empComboBoxActionPerformed(evt);
            }
        });

        jLabel6.setText("Vente : ");

        venteText.setMaximumSize(new java.awt.Dimension(59, 20));
        venteText.setMinimumSize(new java.awt.Dimension(59, 20));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(empComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(submitPayeButt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(heureText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(venteText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(empComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(heureText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(venteText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submitPayeButt)
                .addGap(22, 22, 22))
        );

        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));

        jScrollPane1.setViewportView(affichage);

        listeEmpText.setText("Afficher Liste Employés");
        listeEmpText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listeEmpTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
                    .addComponent(listeEmpText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listeEmpText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       semaineEnCoursField.setText(String.valueOf(ges.getSemaine()));
       contRrField.setText(String.valueOf(ges.getRetraite()));
       assEmpField.setText(String.valueOf(ges.getAssemp()));
       
       String pattern = "yyyy-MM-dd";
       SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);
       String date = simpleDateFormat.format(new Date());       
       dateField.setText(date);
       
       
    }//GEN-LAST:event_formWindowOpened

    private void submitPayeButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitPayeButtActionPerformed
        try{
        String popo = empComboBox.getSelectedItem().toString();
        
        String oregon = popo.replace("[","");
        String lady = oregon.replace("]","");
        String[] parts = lady.split("     ");
        String part1 = parts[0]; // id
        String part2 = parts[1]; // nom
        String part3 = parts[2]; // départ
        double comm = 0;
        int heure = 0;
        heure = Integer.parseInt(heureText.getText());
        //
        
        if (venteText.isEnabled())
        {
            int semaine = ges.getSemaine();
            double vente = Double.parseDouble(venteText.getText());
            int id = Integer.parseInt(part1);
            ges.AjouterVente(vente, semaine, id, part2);            
            String lala = Arrays.toString(ges.Ven.toArray());
            String[] gaps = lala.split("  ");
            String gap1 = gaps[2];
            System.out.println(gap1);
            System.out.println(lala);
            comm = Double.parseDouble(gap1);
            
                      
        }
        else
        {
            venteText.setEnabled(false);
        }        
         
        ges.AjouterPaye(Integer.parseInt(part1), heure, part3, comm, part2);
        venteText.setText("");
        heureText.setText("");
        dispose();
        payeFrame newpayeF = new payeFrame(ges);
        newpayeF.setVisible(true);       
        }                
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_submitPayeButtActionPerformed

    private void empComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empComboBoxActionPerformed
        String popo = empComboBox.getSelectedItem().toString();
        String[] parts = popo.split("     ");
        String part3 = parts[2];
        if ("Ventes".equals(part3))
        {
            venteText.setEnabled(true);
        }
        else
        {
            venteText.setEnabled(false);
        }
        venteText.setText("");
        heureText.setText("");
    }//GEN-LAST:event_empComboBoxActionPerformed

    private void otEmpButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otEmpButtActionPerformed
        // afficher employé et heures d'overtime accumulé
        try{
        String paye[] = new String[ges.Pay.size()];
        String s = "";
            for(int j = 0; j < paye.length; j++)
            {
		paye[j] = ges.Pay.get(j).toString();
                
            }
            for(String a: paye)
		{
                    String[] parts = a.split("  ");            
                    String part0 = parts[0];
                    String part1 = parts[1];
                    String part2 = parts[3];
                    if (!"0".equals(part2))
                    {
                        String lolo = "";
                        lolo += part1 + "    " + part0 + "    " +  part2 +"\n";
                        s += lolo;
                    }
                }
            
            affichage.setText("Nom-|-ID-|-NbHeures\n" + s); 
            }                
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_otEmpButtActionPerformed

    private void otDepartButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otDepartButtActionPerformed
        try{        
        String paye[] = new String[ges.Pay.size()];
        String s = "";
        int resto = 0;
        int commis = 0;
        int maint = 0;
            for(int j =0 ; j < paye.length; j++)
            {
		paye[j] = ges.Pay.get(j).toString();
            }
            for(String a: paye)
		{
                    System.out.println(a);
                    String[] parts = a.split("  ");            
                    String part0 = parts[12];                    
                    String part2 = parts[3];
                        
                    
                        
                    if ("Restaurant".equals(part0))
                        {
                            resto += Integer.parseInt(part2);
                        }
                    if ("Commis/Paysagiste".equals(part0))
                        {
                            commis += Integer.parseInt(part2);   
                        }
                    if ("Maintenance".equals(part0))
                        {
                            maint += Integer.parseInt(part2);  
                        }                 
                    
                }
            
            String lolo = " Restaurant          " + String.valueOf(resto) + " \n Commis/Pays.         " +  String.valueOf(commis) + " \n Maintenance       " + String.valueOf(maint);
            s += lolo;
            
            affichage.setText("Departement-|-NbHeures\n" + s);
            }                
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_otDepartButtActionPerformed

    private void vendeursButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendeursButtActionPerformed
        try{    
            String vent[] = new String[ges.Ven.size()];
            String s = "";
            for(int j =0 ; j < vent.length; j++)
            {
		vent[j] = ges.Ven.get(j).toString();
            }
            for(String a: vent)
		{
                    String[] parts = a.split("  ");            
                    String part0 = parts[0];//id
                    String part1 = parts[1];//vente
                    String part2 = parts[4];//nom
                    if (!"0".equals(part1))
                    {     //a revoir                 
                        String lolo = "";
                        lolo = part2 + "    " + part0 + "    " +  part1 +"\n";
                        s += lolo;
                    }
                }
            
            affichage.setText("Nom-|-ID-|-VenteBrute\n" + s); 
            }                
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_vendeursButtActionPerformed

    private void venteMoisbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venteMoisbuttActionPerformed
        try{    
        String vent[] = new String[ges.Ven.size()];
            
            
            for(int j =0 ; j < vent.length; j++)
            {
		vent[j] = ges.Ven.get(j).toString();
            }
            double venteMensuel[] = new double[13];
            String lolo = "";
            for(String a: vent)
		{
                    String[] parts = a.split("  ");            
                    String venteS = parts[1];
                    String sem = parts[3];
                    
                    int p;
                    double vente = Double.parseDouble(venteS);
                    int week = Integer.parseInt(sem);
                    
                    if (!"0".equals(venteS))
                    {                        
                               
                               System.out.println(String.valueOf(week));
                               if (week >= 0 && week <=3)
                               {
                                   p = 0;
                               }
                               else if (week >= 4 && week <=7)
                               {
                                   p = 1;
                               }
                               else if (week >= 8 && week <=11)
                               {
                                   p = 2;
                               }
                               else if (week >= 12 && week <=15)
                               {
                                   p = 3;
                               }
                               else if (week >= 16 && week <=19)
                               {
                                   p = 4;
                               }
                               else if (week >= 20 && week <=23)
                               {
                                   p = 5;
                               }
                               else if (week >= 24 && week <=27)
                               {
                                   p = 6;
                               }
                               else if (week >= 28 && week <=31)
                               {
                                   p = 7;
                               }
                               else if (week >= 32 && week <=35)
                               {
                                   p = 8;
                               }
                               else if (week >= 36 && week <=39)
                               {
                                   p = 9;
                               }
                               else if (week >= 40 && week <=43)
                               {
                                   p = 10;
                               }
                               else if (week >= 44 && week <=47)
                               {
                                   p = 11;
                               }
                               else if (week >= 48 && week <=51)
                               {
                                   p = 12;
                               }                               
                               else
                               {
                                   p = 11;
                               }
                               System.out.println(String.valueOf(p));
                        
                               for(int q = 0 ; q < venteMensuel.length; q++)
                               {
                                   System.out.println(String.valueOf(vente));
                                   if (p == q)
                                       {
                                       venteMensuel[p] += vente;
                                       }
                               }
                               
                                
                                               

                    }
                
                
                }
                for (int l = 0; l < venteMensuel.length; l++)
                {
                   lolo += String.valueOf(l) + "        " + String.valueOf(venteMensuel[l]) + "\n";
                }
            affichage.setText("Période-|-VenteBrute\n" + lolo); 
            }                
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
            
            
    }//GEN-LAST:event_venteMoisbuttActionPerformed

    private void listeEmpTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listeEmpTextActionPerformed
            try{
        String emp[] = new String[ges.Pay.size()];
            System.out.println(String.valueOf(ges.Pay.size()));
            String s = "";
            for (int i = 0; i < emp.length; i++)
            {
                emp[i] = ges.Pay.get(i).toString();                
            }      
           //(idEmp +"  "+ nom +"  "+ hour + "  "+ ot + "  " + semaineout + "" +salB + "  " + impF + "  " + impP + "  " + retC + "  " + assE + "  " + assB + "  " + salN + "  " + departement)           
            for(String a: emp)
		{
                     
                     String[] parts = a.split("  ");            
                     String idemp  = parts[0];//id
                     String Nom = parts[1];//nom
                     String Depart  = parts[12];//dep
                     String SalBrut  = parts[5];
                     String ImpotFed  = parts[6];
                     String ImpotPro  = parts[7];
                     String Retraite  = parts[8];
                     String AssEmp  = parts[9];
                     String SalaireNet  = parts[11];
                     String lolo = "";                      
                     lolo += idemp + " "+ Nom + "  "+Depart+ "  "+ SalBrut+ "  "+ ImpotFed+ "  "+ ImpotPro+ "  "+ Retraite+ "  "+ AssEmp+ "  "+ SalaireNet + "\n";
                     s += lolo;
                }
            affichage.setText("#Emp|Nom|Depart|SalBrut|ImpotFed|ImpotPro|Retraite|AssEmp|SalaireNet \n" + s); 

          }
        
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e + " Il doit y avoir au moins une paye d'enregistré.");
        }
        
        
        
    }//GEN-LAST:event_listeEmpTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(payeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(payeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(payeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(payeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new payeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane affichage;
    private javax.swing.JTextField assEmpField;
    private javax.swing.JTextField contRrField;
    private javax.swing.JTextField dateField;
    private javax.swing.JComboBox<String> empComboBox;
    private javax.swing.JTextField heureText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton listeEmpText;
    private javax.swing.JButton otDepartButt;
    private javax.swing.JButton otEmpButt;
    private javax.swing.JTextField semaineEnCoursField;
    private javax.swing.JButton submitPayeButt;
    private javax.swing.JButton vendeursButt;
    private javax.swing.JButton venteMoisbutt;
    private javax.swing.JTextField venteText;
    // End of variables declaration//GEN-END:variables

}
